import * as Linking from "expo-linking";
import { router } from "expo-router";
import { act, fireEvent, screen, waitFor, within } from "expo-router/testing-library";

import {
  EMPTY_FEED,
  json,
  renderReadingApp,
  storedSession,
  type ProductRequest,
} from "@/test-utils/readingApp";
import { sourceArticle, sourcesPage, storyDetail } from "@/test-utils/stories";

import { formatTimestamp } from "../format";

// expo-router itself uses expo-linking, so only the outbound call is replaced.
jest.mock("expo-linking", () => ({
  ...jest.requireActual("expo-linking"),
  openURL: jest.fn(async () => true),
}));

// Repository contracts are test inputs only; runtime never falls back to them.
const updating = require("../../../../../docs/contracts/mobile-feed/story-updating.json");
const preparing = require("../../../../../docs/contracts/mobile-feed/story-preparing.json");
const single = require("../../../../../docs/contracts/mobile-feed/story-current-single-source.json");
const contractSources = require("../../../../../docs/contracts/mobile-feed/sources-page.json");

const openURL = Linking.openURL as jest.Mock;

type Reply = Response | (() => Response | Promise<Response>);

/** Scripted product API keyed by `path?cursor`; the last queued reply repeats. */
function productServer(routes: Record<string, Reply[]>) {
  const queues = new Map(Object.entries(routes));
  return async ({ path, query }: ProductRequest) => {
    if (path === "/api/feed") return json(EMPTY_FEED);
    const cursor = query.get("cursor");
    const queue = queues.get(cursor ? `${path}?${cursor}` : path);
    if (!queue) return json({ code: "story_not_found", detail: "The Story was not found." }, 404);
    const reply = queue.length > 1 ? queue.shift()! : queue[0];
    return typeof reply === "function" ? reply() : reply.clone();
  };
}

async function open(routes: Record<string, Reply[]>, url: string) {
  const runtime = await storedSession("reader", productServer(routes));
  const app = await renderReadingApp(runtime, url);
  await waitFor(() => expect(runtime.controller.snapshot().status).toBe("authenticated"));
  return { runtime, app };
}

function calls(runtime: { productCalls: ProductRequest[] }, path: string) {
  return runtime.productCalls
    .filter((call) => call.path === path)
    .map((call) => call.query.get("cursor"));
}

async function endReached() {
  await fireEvent(screen.getByTestId("sources-list"), "endReached", { distanceFromEnd: 0 });
}

const FUTURE_FIELDS = [
  /timeline/i,
  /key points/i,
  /why it matters/i,
  /pulse/i,
  /opinion/i,
  /perspective/i,
  /recommended/i,
];

beforeEach(() => openURL.mockClear());
afterEach(() => jest.restoreAllMocks());

describe("Story details", () => {
  it("shows a CURRENT Story with labelled synthesis, sections and element citations", async () => {
    const story = storyDetail("45", {
      title: "Council approves the river plan",
      summary: "The measure funds restoration work.",
      context: "The plan followed two years of hearings.",
      topics: ["Environment"],
      entities: [{ kind: "ORGANIZATION", display_name: "City Council" }],
      articles: 3,
      sources: 2,
      currentArticles: 4,
      currentSources: 3,
      citedArticleIds: ["101", "102"],
      citations: {
        "101": sourceArticle("101", { publisher: "One News", sourceId: "21" }),
        "102": sourceArticle("102", { publisher: "Two Journal", sourceId: "22" }),
      },
    });
    const { runtime } = await open({ "/api/stories/45": [json(story)] }, "/stories/45");

    expect(
      await screen.findByRole("header", { name: "Council approves the river plan" }),
    ).toBeTruthy();
    expect(screen.getByText("The measure funds restoration work.")).toBeTruthy();
    expect(screen.getByRole("header", { name: "Context" })).toBeTruthy();
    expect(screen.getByText("The plan followed two years of hearings.")).toBeTruthy();
    expect(screen.getByLabelText("Topics: Environment")).toBeTruthy();
    expect(screen.getByText("Organization: City Council")).toBeTruthy();
    expect(
      screen.getByText(
        `Summary generated by Pulso from the cited publications · ${formatTimestamp(story.synthesized_at)}`,
      ),
    ).toBeTruthy();
    expect(screen.getByText("This summary cites 3 articles from 2 sources.")).toBeTruthy();
    expect(screen.getByText("Current sources: 4 articles from 3 sources.")).toBeTruthy();

    // Every TITLE/SUMMARY/CONTEXT element names its publishers without paging.
    for (const element of story.elements as { id: string }[]) {
      const citations = within(screen.getByTestId(`citations-${element.id}`));
      expect(citations.getByText("Cited: One News, Two Journal")).toBeTruthy();
    }
    // Citations resolve from detail metadata, before and without any source page.
    expect(calls(runtime, "/api/stories/45/sources")).toEqual([]);
    for (const invented of FUTURE_FIELDS) expect(screen.queryByText(invented)).toBeNull();
  });

  it("opens a cited publication in the OS browser with no credential", async () => {
    const story = storyDetail("45", {
      citations: { "4501": sourceArticle("4501", { url: "https://one.example.com/river-plan" }) },
    });
    const { runtime, app } = await open({ "/api/stories/45": [json(story)] }, "/stories/45");
    const summary = (story.elements as { id: string; kind: string }[]).find(
      (element) => element.kind === "SUMMARY",
    )!;
    const group = within(await screen.findByTestId(`citations-${summary.id}`));
    await fireEvent.press(group.getByRole("button", { name: "Show cited publications (1)" }));
    await fireEvent.press(group.getByRole("button", { name: "Open publication (external site)" }));

    expect(openURL.mock.calls).toEqual([["https://one.example.com/river-plan"]]);
    // Nothing was fetched from the publisher, so no bearer token could reach it.
    const hosts = runtime.fetch.mock.calls.map(([url]) => new URL(String(url)).host);
    expect(new Set(hosts)).toEqual(new Set(["api.example.com"]));
    expect(app.pathname()).toBe("/stories/45");
  });

  it("keeps a single-source Story honest about missing Context, Entities and dates", async () => {
    await open({ "/api/stories/42": [json(single)] }, "/stories/42");
    expect(await screen.findByRole("header", { name: single.title })).toBeTruthy();
    expect(screen.getByText("This Story has no summary text.")).toBeTruthy();
    expect(screen.queryByRole("header", { name: "Context" })).toBeNull();
    expect(screen.queryByRole("header", { name: "Mentioned" })).toBeNull();
    expect(screen.queryByLabelText(/^Topics:/)).toBeNull();
    // No publication window: nothing is substituted from the Story creation time.
    expect(screen.queryByText(/Latest publication/)).toBeNull();
    expect(screen.getByText("This summary cites 1 article from 1 source.")).toBeTruthy();

    await fireEvent.press(screen.getByRole("button", { name: "Show cited publications (1)" }));
    const row = within(screen.getByTestId("citation-78-101"));
    expect(row.getByText("Example News")).toBeTruthy();
    expect(row.getByText("New weekday service plan")).toBeTruthy();
    expect(
      row.getByText(
        `First seen by Pulso ${formatTimestamp("2026-09-18T11:55:00Z")} · publication time not provided`,
      ),
    ).toBeTruthy();
    expect(row.queryByText(/^Published /)).toBeNull();
    expect(row.queryByText(/^By /)).toBeNull();
    for (const invented of FUTURE_FIELDS) expect(screen.queryByText(invented)).toBeNull();
  });

  it("shows UPDATING with the prior-synthesis notice and time and keeps source access", async () => {
    const { app } = await open(
      {
        "/api/stories/43": [json(updating)],
        "/api/stories/43/sources": [
          json(sourcesPage([sourceArticle("110"), sourceArticle("111")])),
        ],
      },
      "/stories/43",
    );
    const notice = within(await screen.findByTestId("story-updating"));
    expect(notice.getByLabelText("Status: Updating")).toBeTruthy();
    expect(notice.getByText(new RegExp(formatTimestamp(updating.synthesized_at)))).toBeTruthy();
    expect(screen.getByText(updating.elements[1].text)).toBeTruthy();
    expect(screen.getByText("This summary cites 1 article from 1 source.")).toBeTruthy();
    expect(screen.getByText("Current sources: 2 articles from 2 sources.")).toBeTruthy();

    await fireEvent.press(screen.getByRole("button", { name: "View current sources" }));
    await waitFor(() => expect(app.pathname()).toBe("/stories/43/sources"));
    expect(await screen.findByTestId("source-111")).toBeTruthy();
  });

  it("shows PREPARING without a summary and still offers current sources", async () => {
    const { runtime } = await open(
      {
        "/api/stories/44": [json(preparing)],
        "/api/stories/44/sources": [json(sourcesPage([sourceArticle("130")]))],
      },
      "/stories/44",
    );
    const notice = within(await screen.findByTestId("story-preparing"));
    expect(notice.getByLabelText("Status: Preparing")).toBeTruthy();
    expect(screen.queryByRole("header", { name: "Summary" })).toBeNull();
    expect(screen.queryByText(/Summary generated/)).toBeNull();
    expect(screen.queryByText(/This summary cites/)).toBeNull();
    expect(screen.getByText("Current sources: 1 article from 1 source.")).toBeTruthy();

    await fireEvent.press(screen.getByRole("button", { name: "View current sources" }));
    expect(await screen.findByTestId("source-130")).toBeTruthy();
    // A preparing Story has no synthesis context to bind the source list to.
    const sourceCall = runtime.productCalls.find((call) => call.path === "/api/stories/44/sources");
    expect(sourceCall?.query.has("synthesis_id")).toBe(false);
  });

  it.each([
    [404, "story_not_found", "Story not found"],
    [410, "story_unavailable", "Story unavailable"],
  ])("offers a clear way back for %i", async (status, code, title) => {
    const { app } = await open(
      { "/api/stories/9": [json({ code, detail: "x" }, status)] },
      "/stories/9",
    );
    expect(await screen.findByText(title)).toBeTruthy();
    expect(screen.queryByRole("button", { name: "Try again" })).toBeNull();

    await fireEvent.press(screen.getByRole("button", { name: "Go back" }));
    await waitFor(() => expect(app.pathname()).toBe("/"));
  });

  it("retries a transient detail failure", async () => {
    await open(
      {
        "/api/stories/9": [
          json({ code: "server_error", detail: "x" }, 503),
          json(storyDetail("9")),
        ],
      },
      "/stories/9",
    );
    expect(await screen.findByText("Story unavailable right now")).toBeTruthy();
    await fireEvent.press(screen.getByRole("button", { name: "Try again" }));
    expect(await screen.findByText("Story 9 headline")).toBeTruthy();
  });

  it("marks a cited Article that left the Story and keeps it attributable", async () => {
    const story = storyDetail("45", {
      citedArticleIds: ["900"],
      citations: {
        "900": sourceArticle("900", { publisher: "Gone Gazette", current: false, byline: "Ana" }),
      },
    });
    await open({ "/api/stories/45": [json(story)] }, "/stories/45");
    const [first] = await screen.findAllByRole("button", { name: "Show cited publications (1)" });
    await fireEvent.press(first);
    const row = within(screen.getByTestId(/^citation-\d+-900$/));
    expect(row.getByText("Gone Gazette")).toBeTruthy();
    expect(row.getByText("By Ana")).toBeTruthy();
    expect(row.getByText("No longer among this Story's current sources")).toBeTruthy();
  });

  it("reports a failed browser hand-off and lets the reader retry", async () => {
    openURL.mockRejectedValueOnce(new Error("no browser"));
    await open({ "/api/stories/42": [json(single)] }, "/stories/42");
    await fireEvent.press(
      await screen.findByRole("button", { name: "Show cited publications (1)" }),
    );
    const openButton = screen.getByRole("button", { name: "Open publication (external site)" });

    await fireEvent.press(openButton);
    expect(
      await screen.findByText("The publication could not be opened on this device. Try again."),
    ).toBeTruthy();

    await fireEvent.press(openButton);
    await waitFor(() =>
      expect(
        screen.queryByText("The publication could not be opened on this device. Try again."),
      ).toBeNull(),
    );
    expect(openURL).toHaveBeenCalledTimes(2);
  });
});

describe("Story sources", () => {
  it("lists every publication, including repeats from one publisher and withheld links", async () => {
    const story = storyDetail("45");
    await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [
          json(
            sourcesPage([
              sourceArticle("201", { publisher: "One News", sourceId: "21" }),
              sourceArticle("202", { publisher: "One News", sourceId: "21", byline: "Rui" }),
              sourceArticle("203", { publisher: "Three Weekly", sourceId: "23", url: null }),
            ]),
          ),
        ],
      },
      "/stories/45/sources",
    );
    expect(await screen.findByTestId("source-201")).toBeTruthy();
    expect(screen.getAllByText("One News")).toHaveLength(2);
    expect(within(screen.getByTestId("source-202")).getByText("By Rui")).toBeTruthy();

    const withheld = within(screen.getByTestId("source-203"));
    expect(withheld.getByText("Three Weekly")).toBeTruthy();
    expect(withheld.getByText("Article 203 headline")).toBeTruthy();
    expect(withheld.getByText("Link unavailable")).toBeTruthy();
    expect(withheld.queryByRole("button")).toBeNull();
    expect(screen.getByText("All current sources are listed.")).toBeTruthy();
  });

  it("decodes the repository source-page contract, withheld link included", async () => {
    const story = storyDetail("45");
    await open(
      { "/api/stories/45": [json(story)], "/api/stories/45/sources": [json(contractSources)] },
      "/stories/45/sources",
    );
    const withheld = within(await screen.findByTestId("source-9007199254743995"));
    expect(withheld.getByText("Link unavailable")).toBeTruthy();
    const noDate = within(screen.getByTestId("source-9007199254743994"));
    expect(noDate.getByText(/^First seen by Pulso .* publication time not provided$/)).toBeTruthy();
  });

  it("pages through current sources with the synthesis context", async () => {
    const story = storyDetail("45");
    const { runtime } = await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [json(sourcesPage([sourceArticle("201")], "s1"))],
        "/api/stories/45/sources?s1": [json(sourcesPage([sourceArticle("202")]))],
      },
      "/stories/45/sources",
    );
    await screen.findByTestId("source-201");
    await endReached();
    expect(await screen.findByTestId("source-202")).toBeTruthy();
    expect(calls(runtime, "/api/stories/45/sources")).toEqual([null, "s1"]);
    const synthesis = runtime.productCalls
      .filter((call) => call.path === "/api/stories/45/sources")
      .map((call) => call.query.get("synthesis_id"));
    expect(synthesis).toEqual([story.synthesis_id, story.synthesis_id]);
  });

  it("lists a prior-generation citation outside the current source pages", async () => {
    const story = storyDetail("45", {
      citedArticleIds: ["900"],
      citations: { "900": sourceArticle("900", { publisher: "Gone Gazette", current: false }) },
    });
    await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [json(sourcesPage([sourceArticle("201")], "s1"))],
      },
      "/stories/45/sources",
    );
    const earlier = within(await screen.findByTestId("earlier-900"));
    expect(earlier.getByText("Gone Gazette")).toBeTruthy();
    expect(earlier.getByText("No longer among this Story's current sources")).toBeTruthy();
    expect(within(screen.getByTestId("source-201")).queryByText(/No longer among/)).toBeNull();
  });

  it("restarts once when the source context changes, dropping the old pages", async () => {
    const story = storyDetail("45");
    const { runtime } = await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [
          json(sourcesPage([sourceArticle("201")], "s1")),
          json(sourcesPage([sourceArticle("301")], "t1")),
        ],
        "/api/stories/45/sources?s1": [json({ code: "source_context_changed", detail: "x" }, 409)],
        "/api/stories/45/sources?t1": [json(sourcesPage([sourceArticle("302")]))],
      },
      "/stories/45/sources",
    );
    await screen.findByTestId("source-201");
    await endReached();

    expect(await screen.findByTestId("source-301")).toBeTruthy();
    expect(screen.getByTestId("sources-restarted")).toBeTruthy();
    expect(screen.queryByTestId("source-201")).toBeNull();

    await endReached();
    expect(await screen.findByTestId("source-302")).toBeTruthy();
    expect(screen.queryByTestId("source-201")).toBeNull();
    expect(calls(runtime, "/api/stories/45/sources")).toEqual([null, "s1", null, "t1"]);
  });

  it("stops after a second context change and waits for an explicit reload", async () => {
    const story = storyDetail("45");
    const changed = json({ code: "source_context_changed", detail: "x" }, 409);
    const { runtime } = await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [
          json(sourcesPage([sourceArticle("201")], "s1")),
          json(sourcesPage([sourceArticle("301")], "t1")),
          json(sourcesPage([sourceArticle("401")])),
        ],
        "/api/stories/45/sources?s1": [changed],
        "/api/stories/45/sources?t1": [changed],
      },
      "/stories/45/sources",
    );
    await screen.findByTestId("source-201");
    await endReached();
    await screen.findByTestId("source-301");
    await endReached();

    expect(await screen.findByTestId("sources-changed-again")).toBeTruthy();
    // The loaded page is kept, and further scrolling does not loop.
    expect(screen.getByTestId("source-301")).toBeTruthy();
    await endReached();
    await act(async () => undefined);
    expect(calls(runtime, "/api/stories/45/sources")).toEqual([null, "s1", null, "t1"]);

    await fireEvent.press(screen.getByRole("button", { name: "Reload sources" }));
    expect(await screen.findByTestId("source-401")).toBeTruthy();
    expect(screen.queryByTestId("sources-changed-again")).toBeNull();
    expect(calls(runtime, "/api/stories/45/sources")).toEqual([null, "s1", null, "t1", null]);
  });

  it("keeps loaded sources when a page fails and retries on request", async () => {
    const story = storyDetail("45");
    await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [json(sourcesPage([sourceArticle("201")], "s1"))],
        "/api/stories/45/sources?s1": [
          json({ code: "server_error", detail: "x" }, 503),
          json(sourcesPage([sourceArticle("202")])),
        ],
      },
      "/stories/45/sources",
    );
    await screen.findByTestId("source-201");
    await endReached();
    expect(await screen.findByText("More sources could not be loaded.")).toBeTruthy();
    expect(screen.getByTestId("source-201")).toBeTruthy();
    await fireEvent.press(screen.getByRole("button", { name: "Try again" }));
    expect(await screen.findByTestId("source-202")).toBeTruthy();
  });

  it("shows 410 on the source route with a way back", async () => {
    const { app } = await open(
      { "/api/stories/45": [json({ code: "story_unavailable", detail: "x" }, 410)] },
      "/stories/45/sources",
    );
    expect(await screen.findByText("Story unavailable")).toBeTruthy();
    await fireEvent.press(screen.getByRole("button", { name: "Go to Feed" }));
    await waitFor(() => expect(app.pathname()).toBe("/"));
  });

  it("preserves Story and source context across a publisher visit and back", async () => {
    const story = storyDetail("45");
    const { runtime, app } = await open(
      {
        "/api/stories/45": [json(story)],
        "/api/stories/45/sources": [json(sourcesPage([sourceArticle("201")], "s1"))],
        "/api/stories/45/sources?s1": [json(sourcesPage([sourceArticle("202")]))],
      },
      "/stories/45",
    );
    await fireEvent.press(await screen.findByRole("button", { name: "View current sources" }));
    await screen.findByTestId("source-201");
    await endReached();
    await screen.findByTestId("source-202");

    await fireEvent.press(
      within(screen.getByTestId("source-202")).getByRole("button", {
        name: "Open publication (external site)",
      }),
    );
    expect(openURL).toHaveBeenCalledWith("https://publisher21.example/articles/202");
    expect(app.pathname()).toBe("/stories/45/sources");
    expect(screen.getByTestId("source-201")).toBeTruthy();
    expect(screen.getByTestId("source-202")).toBeTruthy();

    await act(() => router.back());
    await waitFor(() => expect(app.pathname()).toBe("/stories/45"));
    expect(screen.getByText("Story 45 headline")).toBeTruthy();
    // Returning reused the cached detail and source pages.
    expect(calls(runtime, "/api/stories/45")).toHaveLength(1);
    expect(calls(runtime, "/api/stories/45/sources")).toEqual([null, "s1"]);
  });
});
