/**
 * Wording for factual Story metadata. Every label names what the value is: a
 * Story's creation time is never its publication time, a synthesis time is
 * never a reporting time, a first-seen time is never a publication time, and a
 * source count is never "verified" or "independent".
 */

/** "1 source", "2 sources"; zero uses the plural. */
export function countLabel(count: number, singular: string, plural: string): string {
  return `${count} ${count === 1 ? singular : plural}`;
}

const DATE_TIME = new Intl.DateTimeFormat(undefined, {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "2-digit",
  minute: "2-digit",
});

/** A wire timestamp in the reader's locale and time zone. */
export function formatTimestamp(iso: string): string {
  return DATE_TIME.format(new Date(iso));
}

/**
 * The Story's publication window as reported by its member Articles. Story
 * creation time is not publication time, so a missing window stays missing.
 */
export function storyPublicationLabel(story: {
  first_published_at: string | null;
  last_published_at: string | null;
}): string | null {
  const latest = story.last_published_at ?? story.first_published_at;
  return latest === null ? null : `Latest publication ${formatTimestamp(latest)}`;
}

/** Generation time of the system synthesis; never a reporting or publication time. */
export function synthesisLabel(synthesizedAt: string): string {
  return `Summary generated by Pulso from the cited publications · ${formatTimestamp(synthesizedAt)}`;
}

/** "Published …" only for a real publication time; otherwise the labelled first-seen time. */
export function articleTimeLabel(article: {
  published_at: string | null;
  first_seen_at: string;
}): string {
  return article.published_at === null
    ? `First seen by Pulso ${formatTimestamp(article.first_seen_at)} · publication time not provided`
    : `Published ${formatTimestamp(article.published_at)}`;
}

/** "2 articles from 1 source" for a stated scope. */
export function articlesFromSources(articles: number, sources: number): string {
  return `${countLabel(articles, "article", "articles")} from ${countLabel(sources, "source", "sources")}`;
}
