# Generated by Django 5.2.17 on 2026-09-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("homepage_url", models.URLField(blank=True)),
                ("default_language", models.CharField(default="en", max_length=35)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.TextField(blank=True)),
                ("canonical_url", models.URLField(unique=True)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                ("byline", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(max_length=35)),
                ("content_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("first_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="news.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_key_kind",
                    models.CharField(
                        choices=[
                            ("EXTERNAL_ID", "External ID"),
                            ("CANONICAL_URL", "Canonical URL"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_key", models.TextField()),
                ("external_id", models.TextField(blank=True)),
                ("url", models.TextField(blank=True)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No outcome"),
                            ("ARTICLE_CREATED", "Article created"),
                            ("ARTICLE_UPDATED", "Article updated"),
                            ("IDENTITY_DUPLICATE", "Identity duplicate"),
                            ("CONTENT_DUPLICATE", "Content duplicate"),
                            ("IDENTITY_CONFLICT", "Identity conflict"),
                            ("SOURCE_IDENTITY_CONFLICT", "Source identity conflict"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=64)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_revisions",
                        to="news.article",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="news.rawarticle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="raw_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="normalized_articles",
                to="news.rawarticle",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="news.source",
            ),
        ),
        migrations.CreateModel(
            name="SourceEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("RSS", "RSS"), ("JSON_FEED", "JSON Feed")], max_length=16
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("fetch_interval_seconds", models.PositiveIntegerField(default=900)),
                ("adapter_config", models.JSONField(blank=True, default=dict)),
                ("etag", models.CharField(blank=True, max_length=255)),
                ("last_modified", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="endpoints",
                        to="news.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rawarticle",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_articles",
                to="news.sourceendpoint",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="news.sourceendpoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceendpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("fetch_interval_seconds__gt", 0)),
                name="news_endpoint_interval_gt_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="rawarticle",
            index=models.Index(
                fields=["endpoint", "external_key_kind", "external_key"],
                name="news_raw_identity_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawarticle",
            index=models.Index(fields=["status", "created_at"], name="news_raw_status_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="rawarticle",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "external_key_kind", "external_key", "payload_hash"),
                name="news_raw_identity_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("source", "external_id"),
                name="news_article_source_external_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_url", ""), _negated=True),
                name="news_article_canonical_url_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duplicate_of__isnull", True),
                    models.Q(("duplicate_of_id", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="news_article_not_self_duplicate",
            ),
        ),
    ]
