# Generated by Django 5.2.17 on 2026-09-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trigger", models.CharField(max_length=32)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL", "Partial"),
                            ("NO_CHANGE", "No change"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("error_kind", models.CharField(blank=True, max_length=32)),
                ("error_message", models.CharField(blank=True, max_length=512)),
                ("will_retry", models.BooleanField(default=False)),
                ("items_received", models.PositiveIntegerField(default=0)),
                ("items_rejected", models.PositiveIntegerField(default=0)),
                ("raw_created", models.PositiveIntegerField(default=0)),
                ("raw_unchanged", models.PositiveIntegerField(default=0)),
                ("raw_changed", models.PositiveIntegerField(default=0)),
                ("items_processed", models.PositiveIntegerField(default=0)),
                ("items_failed", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="news.sourceendpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rawarticle",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_articles",
                to="news.ingestionrun",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(
                fields=["endpoint", "-started_at"], name="news_run_endpoint_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(fields=["status", "started_at"], name="news_run_status_started_idx"),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gte", 0)), name="news_run_attempt_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("items_received__gte", 0),
                    ("items_rejected__gte", 0),
                    ("raw_created__gte", 0),
                    ("raw_unchanged__gte", 0),
                    ("raw_changed__gte", 0),
                    ("items_processed__gte", 0),
                    ("items_failed__gte", 0),
                ),
                name="news_run_counters_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration_ms__isnull", True), ("duration_ms__gte", 0), _connector="OR"
                ),
                name="news_run_duration_nonnegative",
            ),
        ),
    ]
