# Generated by Django 5.2.17 on 2026-09-17 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_ingestionrun_dedup_counters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("language", models.CharField(max_length=35)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["status"], name="news_story_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="StoryArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("associated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CREATED_STORY", "Created story"),
                            ("MATCHED", "Matched"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("similarity", models.FloatField(blank=True, null=True)),
                ("matcher_key", models.CharField(blank=True, max_length=128)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="story_articles",
                        to="news.article",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_articles",
                        to="news.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["story", "associated_at"], name="news_storyart_membership_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story", "article"), name="news_storyarticle_story_article_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("article",),
                        name="news_storyarticle_one_primary_per_article",
                    ),
                ],
            },
        ),
    ]
