# Generated by Django 5.2.17 on 2026-09-18 00:07

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_story_storyarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_key", models.CharField(max_length=255)),
                ("dimension", models.PositiveSmallIntegerField()),
                ("vector", pgvector.django.vector.VectorField()),
                ("input_chars", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "article",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embeddings",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["model_key"], name="news_articleemb_model_key_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "model_key"), name="news_articleemb_article_model_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("model_key", ""), _negated=True),
                        name="news_articleemb_model_key_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("dimension__gte", 1), ("dimension__lte", 2000)),
                        name="news_articleemb_dimension_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "dimension",
                                models.Func(
                                    models.F("vector"),
                                    function="vector_dims",
                                    output_field=models.IntegerField(),
                                ),
                            )
                        ),
                        name="news_articleemb_vector_matches_dimension",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_key", models.CharField(max_length=255)),
                ("dimension", models.PositiveSmallIntegerField()),
                ("vector", pgvector.django.vector.VectorField()),
                ("member_count", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "story",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="news.story",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["model_key"], name="news_storyemb_model_key_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story", "model_key"), name="news_storyemb_story_model_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("member_count__gte", 1)),
                        name="news_storyemb_member_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("model_key", ""), _negated=True),
                        name="news_storyemb_model_key_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("dimension__gte", 1), ("dimension__lte", 2000)),
                        name="news_storyemb_dimension_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "dimension",
                                models.Func(
                                    models.F("vector"),
                                    function="vector_dims",
                                    output_field=models.IntegerField(),
                                ),
                            )
                        ),
                        name="news_storyemb_vector_matches_dimension",
                    ),
                ],
            },
        ),
    ]
