# Generated by Django 5.2.17 on 2026-09-18 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_articleembedding_storyembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleStoryProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EMBEDDED", "Embedded"),
                            ("MATCHED", "Matched"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_kind", models.CharField(blank=True, max_length=32)),
                ("error_message", models.CharField(blank=True, max_length=512)),
                ("embedding_model_key", models.CharField(blank=True, max_length=255)),
                ("matcher_key", models.CharField(blank=True, max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="story_processing",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "embedding_model_key", "matcher_key"],
                        name="news_storyproc_reconcile_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "MATCHED"), _negated=True),
                            models.Q(
                                models.Q(("embedding_model_key", ""), _negated=True),
                                models.Q(("matcher_key", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="news_storyproc_matched_has_keys",
                    )
                ],
            },
        ),
    ]
