# Generated by Django 5.2.17 on 2026-09-18 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_articlestoryprocessing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("ORGANIZATION", "Organization"),
                            ("PLACE", "Place"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("normalized_key", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "normalized_key"), name="news_entity_kind_key_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField()),
                ("model_key", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="story_entities",
                        to="news.entity",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_entities",
                        to="news.story",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story", "entity"), name="news_storyentity_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("model_key", ""), _negated=True),
                        name="news_storyentity_model_key_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                        name="news_storyentity_score_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField()),
                ("model_key", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "story",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_topics",
                        to="news.story",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="story_topics",
                        to="news.topic",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story", "topic"), name="news_storytopic_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("model_key", ""), _negated=True),
                        name="news_storytopic_model_key_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                        name="news_storytopic_score_range",
                    ),
                ],
            },
        ),
    ]
