# Generated by Django 5.2.17 on 2026-09-18 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_topic_entity_storytopic_storyentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorySynthesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_key", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_current", models.BooleanField(default=True)),
                ("member_signature", models.CharField(max_length=64)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syntheses",
                        to="news.story",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorySynthesisElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TITLE", "Title"),
                            ("SUMMARY", "Summary"),
                            ("CONTEXT", "Context"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "synthesis",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="news.storysynthesis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorySynthesisElementSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="synthesis_sources",
                        to="news.article",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="news.storysynthesiselement",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="storysynthesis",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("story",),
                name="news_synthesis_one_current_per_story",
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesis",
            constraint=models.CheckConstraint(
                condition=models.Q(("model_key", ""), _negated=True),
                name="news_synthesis_model_key_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesis",
            constraint=models.CheckConstraint(
                condition=models.Q(("member_signature", ""), _negated=True),
                name="news_synthesis_signature_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesiselement",
            constraint=models.UniqueConstraint(
                fields=("synthesis", "kind", "position"), name="news_synthesis_element_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesiselement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "TITLE")),
                fields=("synthesis",),
                name="news_synthesis_one_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesiselement",
            constraint=models.CheckConstraint(
                condition=models.Q(("text", ""), _negated=True), name="news_synthesis_element_text"
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesiselementsource",
            constraint=models.UniqueConstraint(
                fields=("element", "article"), name="news_synthesis_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="storysynthesiselementsource",
            constraint=models.UniqueConstraint(
                fields=("element", "position"), name="news_synthesis_source_order"
            ),
        ),
    ]
