# Generated by Django 5.2.17 on 2026-09-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_story_synthesis"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="article_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="first_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="last_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="member_signature",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="story",
            name="refresh_error",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="story",
            name="refresh_state",
            field=models.CharField(
                choices=[("CURRENT", "Current"), ("STALE", "Stale"), ("FAILED", "Failed")],
                default="STALE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storyembedding",
            name="member_signature",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="storyentity",
            name="member_signature",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="storytopic",
            name="member_signature",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
