# Generated by Django 5.2.17 on 2026-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_story_article_count_story_first_published_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlestoryprocessing",
            name="matcher_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="storyarticle",
            name="matcher_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
